# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello world"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello world"

  publish:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello world"

  test1-ubuntu:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Running test on ubuntu-latest"

  test1-windows:
    needs: test1-ubuntu
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Running test on windows-latest"

  test1-macos:
    needs: test1-windows
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Running test on macos-latest"
